import React from 'react';

function Head() {
	return (
		<React.Fragment>
			<title>Petionary 프로젝트입니다.</title>
			<meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
			<meta name={'description'} content={'Generated by create next app'} />
			<link rel={'icon'} href='/mdi_pets.svg' />
		</React.Fragment>
	);
}

export default Head;
