import ReactQueryProvider from '@/providers/ReactQueryProvider';
import RecoilRootProvider from '@/providers/RecoilRootProvider';
import StyledComponentsRegistry from '@/providers/StyledComponentsRegistry';
import type {Metadata} from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: 'Petionary',
    description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html>
            <body>
                <StyledComponentsRegistry>
                    <ReactQueryProvider>
                        <RecoilRootProvider>{children} </RecoilRootProvider>
                    </ReactQueryProvider>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
