import ReactQueryProvider from '@/providers/ReactQueryProvider';
import type {Metadata} from 'next';
import React from 'react';
import Providers from '@/providers/Providers';
import RecoilRootProvider from '@/providers/RecoilRootProvider';

export const metadata: Metadata = {
	title: 'Petionary',
	description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html>
			<body>
				<Providers>
					<ReactQueryProvider>
						<RecoilRootProvider>{children} </RecoilRootProvider>
					</ReactQueryProvider>
				</Providers>
			</body>
		</html>
	);
}
